{% set name = "parliament" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf40d5f5732bcf831fdb1a13f71c3cf4f3bdb8c8d9685592ecdd6d84675b947e

build:
  number: 0
  noarch: python
  entry_points:
    - parliament=parliament.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nose
    - pip
    - python >=3.6
  run:
    - boto3
    - jmespath
    - json-cfg
    - python >=3.6
    - pyyaml

test:
  imports:
    - parliament
    - parliament.community_auditors
  commands:
    - pip check
    - parliament --help
  requires:
    - pip

about:
  home: https://github.com/duo-labs/parliament
  summary: parliament audits your AWS IAM policies
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    parliament is an AWS IAM linting library. It reviews policies looking for problems such as:

    * malformed json
    * missing required elements
    * incorrect prefix and action names
    * incorrect resources or conditions for the actions provided
    * type mismatches
    * bad policy patterns
  dev_url: https://github.com/duo-labs/parliament

extra:
  recipe-maintainers:
    - BastianZim
